In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
df = pd.read_excel(r'C:/BEPEC Python Material/Machine Learning/Logistic Regression/credit_card.xlsx', engine='openpyxl')
df.head()

Unnamed: 0         X1   X2         X3        X4   X5     X6     X7     X8  \
0         ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3   
1          1      20000    2          2         1   24      2      2      0   
2          2     120000    2          2         2   26      0      2      0   
3          3      90000    2          2         2   34      0      0      0   
4          4      50000    2          2         1   37      0      0      0   

      X9  ...        X15        X16        X17       X18       X19       X20  \
0  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3   
1      0  ...          0          0          0         0       689         0   
2      0  ...       3272       3455       3261         0      1000      1000   
3      0  ...      14331      14948      15549      1518      1500      1000   
4      0  ...      28314      28959      29547      2000      2019      1200   

        X21       X22       X23                           Y  
0  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1         0         0         0                           1  
2      1000         0      2000                           1  
3      1000      1000      5000                           0  
4      1100      1069      1000                           0  

[5 rows x 25 columns]

In [3]:
column_names = df.loc[0,:]
column_names = column_names.to_list()
l1 = df.columns
l1 = l1.to_list()
df.columns = column_names
df.rename(columns= {'PAY_0':'PAY_1'}, inplace=True)
df.drop([0], inplace=True)
column_names = df.columns
for column in column_names:
    df[column] = pd.to_numeric(df[column]) 
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
1   1      20000    2          2         1   24      2      2      0      0   
2   2     120000    2          2         2   26      0      2      0      0   
3   3      90000    2          2         2   34      0      0      0      0   
4   4      50000    2          2         1   37      0      0      0      0   
5   5      50000    1          2         1   57      0      0      0      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
1  ...          0          0          0         0       689         0   
2  ...       3272       3455       3261         0      1000      1000   
3  ...      14331      14948      15549      1518      1500      1000   
4  ...      28314      28959      29547      2000      2019      1200   
5  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1         0         0         0                           1  
2      1000         0      2000                           1  
3      1000      1000      5000                           0  
4      1100      1069      1000                           0  
5      9000       689       679                           0  

[5 rows x 25 columns]

In [4]:
df.drop(columns={'ID'}, inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30000 entries, 1 to 30000
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   30000 non-null  int64
 1   SEX                         30000 non-null  int64
 2   EDUCATION                   30000 non-null  int64
 3   MARRIAGE                    30000 non-null  int64
 4   AGE                         30000 non-null  int64
 5   PAY_1                       30000 non-null  int64
 6   PAY_2                       30000 non-null  int64
 7   PAY_3                       30000 non-null  int64
 8   PAY_4                       30000 non-null  int64
 9   PAY_5                       30000 non-null  int64
 10  PAY_6                       30000 non-null  int64
 11  BILL_AMT1                   30000 non-null  int64
 12  BILL_AMT2                   30000 non-null  int64
 13  BILL_AMT3                   30000 non-null  int64
 14  BILL_A

In [6]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(X.shape)
print(y.shape)

(30000, 23)
(30000,)


In [7]:
from sklearn.model_selection import StratifiedShuffleSplit

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=0)
print(sss.get_n_splits(X, y))
print(sss)

train_idx = 0
test_idx = 0
for train_idx , test_idx in sss.split(X,y):
    X_train  , X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train  , y_test = y.iloc[train_idx], y.iloc[test_idx]

1
StratifiedShuffleSplit(n_splits=1, random_state=0, test_size=0.1,
            train_size=None)


In [8]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(y.value_counts())
print(y_train.value_counts())
print(y_test.value_counts())

(27000, 23)
(3000, 23)
(27000,)
(3000,)
0    23364
1     6636
Name: default payment next month, dtype: int64
0    21028
1     5972
Name: default payment next month, dtype: int64
0    2336
1     664
Name: default payment next month, dtype: int64


In [26]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(loss = 'exponential' , n_estimators=450, learning_rate=0.3 , min_impurity_decrease=0.05,  
                                 max_depth=5,  random_state=0 ).fit(X_train, y_train)
print(clf.score(X_train , y_train))

0.926


In [27]:
y_pred = clf.predict(X_test)
print(clf.score(X_test , y_test))

0.8126666666666666


In [28]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , y_pred))

0.8126666666666666


In [29]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, y_pred),"\n------------------")
#print(metrics.confusion_matrix(y_train, train_predicted))

[[2185  151]
 [ 411  253]] 
------------------


In [30]:
print(metrics.classification_report(y_test, y_pred  ))

              precision    recall  f1-score   support

           0       0.84      0.94      0.89      2336
           1       0.63      0.38      0.47       664

    accuracy                           0.81      3000
   macro avg       0.73      0.66      0.68      3000
weighted avg       0.79      0.81      0.79      3000



In [31]:
clf.train_score_

array([0.78067459, 0.75031667, 0.7320539 , 0.72061088, 0.71303138,
       0.70688136, 0.70316771, 0.69976798, 0.69598236, 0.69394395,
       0.69174303, 0.69012026, 0.68806696, 0.68577567, 0.68508726,
       0.68379757, 0.68308798, 0.68217854, 0.68068249, 0.67864466,
       0.67703019, 0.67522802, 0.67390819, 0.67228064, 0.67070462,
       0.66988727, 0.66849212, 0.66725207, 0.66637422, 0.66530565,
       0.66471198, 0.66405569, 0.66348212, 0.66242113, 0.66054709,
       0.65904644, 0.65760386, 0.65666213, 0.65592341, 0.65506598,
       0.65382326, 0.65237613, 0.65075549, 0.64906048, 0.64787968,
       0.64746029, 0.64654514, 0.6450228 , 0.64414067, 0.64365751,
       0.64248923, 0.64102986, 0.63952365, 0.6385344 , 0.6373937 ,
       0.63577186, 0.63427678, 0.63316098, 0.63177164, 0.63092345,
       0.62997395, 0.62893824, 0.62794709, 0.62709242, 0.62613748,
       0.62523458, 0.62477782, 0.62426403, 0.62380318, 0.62310928,
       0.62190402, 0.62104644, 0.62076808, 0.61942254, 0.61875

In [40]:
l1 = [1,2,3,4]
l2 = [4,5,6 , 7]
for x , y in enumerate(l1):
    print(x , y)
for i in zip(l1,l2):
           print(i)

0 1
1 2
2 3
3 4
(1, 4)
(2, 5)
(3, 6)
(4, 7)


In [14]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [15]:
clf = AdaBoostClassifier(  DecisionTreeClassifier(max_depth=2) , n_estimators=250, random_state=0 , learning_rate = 0.1)
clf.fit(X_train , y_train)
clf.score(X_train , y_train)

0.8231851851851851

In [16]:
y_pred = clf.predict(X_test)
print(clf.score(X_test , y_test))

0.818


In [17]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , y_pred))

0.818


In [18]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, y_pred),"\n------------------")
#print(metrics.confusion_matrix(y_train, train_predicted))

[[2218  118]
 [ 428  236]] 
------------------


In [19]:
print(metrics.classification_report(y_test, y_pred  ))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      2336
           1       0.67      0.36      0.46       664

    accuracy                           0.82      3000
   macro avg       0.75      0.65      0.68      3000
weighted avg       0.80      0.82      0.80      3000



In [20]:
clf.base_estimator_

DecisionTreeClassifier(max_depth=2)

In [21]:
print(X_train.shape[1])
clf.feature_importances_

23


array([0.10151564, 0.01073535, 0.02201084, 0.01527723, 0.01531236,
       0.08090321, 0.01128699, 0.01663833, 0.00921373, 0.00947929,
       0.02096106, 0.09020132, 0.06528646, 0.06586627, 0.07776305,
       0.02632692, 0.03664764, 0.05255861, 0.05614905, 0.07419067,
       0.04201184, 0.03981524, 0.0598489 ])

In [23]:
clf.get_params()

{'algorithm': 'SAMME.R',
 'base_estimator__ccp_alpha': 0.0,
 'base_estimator__class_weight': None,
 'base_estimator__criterion': 'gini',
 'base_estimator__max_depth': 2,
 'base_estimator__max_features': None,
 'base_estimator__max_leaf_nodes': None,
 'base_estimator__min_impurity_decrease': 0.0,
 'base_estimator__min_impurity_split': None,
 'base_estimator__min_samples_leaf': 1,
 'base_estimator__min_samples_split': 2,
 'base_estimator__min_weight_fraction_leaf': 0.0,
 'base_estimator__random_state': None,
 'base_estimator__splitter': 'best',
 'base_estimator': DecisionTreeClassifier(max_depth=2),
 'learning_rate': 0.1,
 'n_estimators': 250,
 'random_state': 0}

AttributeError: 'AdaBoostClassifier' object has no attribute 'train_score_'